Repository CPS-IT/frontend-asset-handler, pull requests merged in 2022-10, with the labels that each got.

#41 [BUGFIX] Skip codeclimate coverate report if secret is not available
  .github/workflows/tests.yaml
Labels: bug

#46 [FEATURE] Support regular expression in branch map
  docs/config/environments.md
  src/Asset/Environment/Map/MapFactory.php
  src/Asset/Environment/Map/Pair.php
  tests/Unit/Asset/Environment/Map/MapFactoryTest.php
Labels: enhancement

#47 [BUGFIX] fix duplicate test assertion
  src/Command/FetchAssetsCommand.php
  tests/Unit/Command/FetchAssetsCommandTest.php
Labels: bug

#40 [FEATURE] lower error level to warning for already downloaded revisions
  src/Command/FetchAssetsCommand.php
  tests/Unit/Command/FetchAssetsCommandTest.php
Labels: enhancement

#52 [BUGFIX] Pass on strategy when fetching assets for fallback environment
  src/Command/FetchAssetsCommand.php
  tests/Unit/Command/FetchAssetsCommandTest.php
  tests/Unit/Fixtures/Classes/DummyHandler.php
Labels: bug

#55 [BUGFIX] Exclude various dev-only files from being exported
  .gitattributes
Labels: bug

#58 [TASK] Flag classes being part of the public API
  src/Asset/Asset.php
  src/Asset/Definition/AssetDefinitionFactory.php
  src/Asset/Definition/Source.php
  src/Asset/Definition/Target.php
  src/Asset/Definition/Vcs.php
  src/Asset/Environment/EnvironmentResolver.php
  src/Asset/Environment/Map/MapFactory.php
  src/Config/ConfigFacade.php
  src/Config/Parser/Parser.php
  src/Config/Parser/ParserInstructions.php
  src/Handler/HandlerFactory.php
  src/Helper/ArrayHelper.php
  src/Helper/FilesystemHelper.php
  src/Helper/StringHelper.php
  src/Helper/VcsHelper.php
  src/Processor/ProcessorFactory.php
  src/Provider/ProviderFactory.php
  src/Strategy/DecisionMaker.php
  src/Vcs/VcsProviderFactory.php
Labels: maintenance

#57 [BUGFIX] Assure public API classes are publicly available services
  config/services.yaml
Labels: bug

#59 [DOCS] Fix and align code example of API usage
  docs/usage/api-usage.md
Labels: documentation

#66 [BUGFIX] Streamline base path handling for relative paths
  docs/config/target.md
  src/Config/ConfigFacade.php
  src/Config/Initialization/Step/ConfigFileStep.php
  src/DependencyInjection/ContainerFactory.php
  src/Helper/FilesystemHelper.php
  src/Traits/TargetPathBuilderTrait.php
  tests/Unit/Helper/FilesystemHelperTest.php
Labels: bug

#69 [TASK] Switch to `ncipollo/release-action` for new releases
  .github/workflows/release.yaml
Labels: maintenance
