Repository CPS-IT/frontend-asset-handler, pull requests merged in 2024-11, with the labels that each got.

#605 [TASK] Switch to `ramsey/composer-install@v3`
  .github/workflows/cgl.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
Labels: maintenance

#612 [BUGFIX] Add return type hint to doRun method
  src/Console/Application.php
Labels: bug

#616 [DOCS] Fix API usage code examples
  docs/usage/api-usage.md
Labels: documentation
